=== nwithan8/unraid_templates/templates/template_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Container">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="^[A-Za-z0-9\s\-]*$"/>  <!-- Non-empty string, letters, numbers, spaces, hyphens -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Repository" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[\w\-_.]+/[\w\-_/]+:[\w\-_.]+"/> <!-- Example: author/repo:tag -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Registry" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[\S\s]+"/> <!-- Non-empty string -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Branch" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Tag" type="xs:string"/>
                            <xs:element name="TagDescription" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Network" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="WebUI" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://\[IP\]:\[PORT:\d{1,5}\].*"/> <!-- Technically allows ports larger than 65535 -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Shell" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Privileged" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Support" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+"/> <!-- URL pattern -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Project" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+"/> <!-- URL pattern -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Overview" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[\S\s]+"/> <!-- Non-empty string -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Beta" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="True"/>
                            <xs:enumeration value="False"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Category" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="([^:]+:[^:\s]*\s?)+"/> <!-- Any amount of "Category:" or "Category:Subcategory" elements-->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ExtraSearchTerms" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Icon" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+\.(png|jpg|jpeg|gif|svg)"/> <!-- URL pattern for image files -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Banner" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+\.(png|jpg|jpeg|gif|svg)"/> <!-- URL pattern for image files -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="TemplateURL" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+\.xml"/> <!-- URL pattern for XML files -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Screenshot" minOccurs="0" maxOccurs="unbounded">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+\.(png|jpg|jpeg|gif|svg)"/> <!-- URL pattern for image files -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Maintainer" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="WebPage">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="https?://.+"/> <!-- URL pattern -->
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Changes" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Requires" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="ExtraParams" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="PostArgs" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Config" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="Name" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[\S\s]+"/> <!-- Non-empty string -->
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="Target" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[\S\s]+"/> <!-- Non-empty string -->
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="Default" type="xs:string" use="required"/>
                                <xs:attribute name="Mode" type="xs:string"/>
                                <xs:attribute name="Description" type="xs:string" use="required"/>
                                <xs:attribute name="Type" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="Port"/>
                                            <xs:enumeration value="Path"/>
                                            <xs:enumeration value="Variable"/>
                                            <xs:enumeration value="Label"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="Display" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="always"/>
                                            <xs:enumeration value="always-hide"/>
                                            <xs:enumeration value="advanced"/>
                                            <xs:enumeration value="advanced-hide"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="Required" type="xs:boolean" use="required"/>
                                <xs:attribute name="Mask" type="xs:boolean" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== nwithan8/unraid_templates/templates/gift_manager.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/template_schema.xsd template_schema.xsd">
    <Name>GiftManager</Name>
    <Repository>icbest/giftmanager:latest</Repository>
    <Registry>https://hub.docker.com/r/icbest/giftmanager</Registry>
    <Branch>
        <Tag>latest</Tag>
        <TagDescription>Latest stable release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <WebUI>http://[IP]:[PORT:5000]/</WebUI>
    <Privileged>false</Privileged>
    <Support>https://gift.icbest.ca/</Support>
    <Project>https://giftmanagerdemo.pages.dev/</Project>
    <Overview>
        Gift ideas manager for families
    </Overview>
    <Beta>False</Beta>
    <Category>Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>gifts presents ideas manager family wishlist Christmas holiday party planner</ExtraSearchTerms>
    <Icon>https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/gift-manager-icon.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/gift_manager.xml</TemplateURL>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2025-10-26

        Initial release
    </Changes>
    <Requires>
        Optionally provide the Docker Socket to enable settings reload within the container.
    </Requires>
    <Config Name="Web UI Port" Target="5000" Default="5000" Mode="tcp" Description="Container Port: 5000" Type="Port" Display="always-hide" Required="true" Mask="false">5000</Config>
    <Config Name="Docker Socket" Target="/var/run/docker.sock" Default="/var/run/docker.sock" Mode="ro" Description="Optional, path to the Docker socket. Provide to enable settings reload inside application." Type="Path" Display="always" Required="true" Mask="false">/var/run/docker.sock</Config>
    <Config Name="App Data" Target="/app/data" Default="/mnt/user/appdata/gift_manager/data" Description="Path to the data folder" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/gift_manager/data</Config>
</Container>

=== nwithan8/unraid_templates/templates/tvx.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/template_schema.xsd template_schema.xsd">
    <Name>TVx</Name>
    <Repository>ghcr.io/dopeytree/tvx:latest</Repository>
    <Registry>ghcr.io/dopeytree/tvx</Registry>
    <Branch>
        <Tag>latest</Tag>
        <TagDescription>Latest stable release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <WebUI>http://[IP]:[PORT:8777]/</WebUI>
    <Privileged>false</Privileged>
    <Support>https://github.com/dopeytree/TVx/issues</Support>
    <Project>https://github.com/dopeytree/TVx</Project>
    <Overview>
        A vintage TV experience for M3U playlists
    </Overview>
    <Beta>False</Beta>
    <Category>MediaApp:Video Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>m3u xml iptv tv guide crt vintage player plex emby jellyfin tunarr dizquetv ersatz</ExtraSearchTerms>
    <Icon>https://raw.githubusercontent.com/dopeytree/TVx/main/public/logo.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/tvx.xml</TemplateURL>
    <Screenshot>https://raw.githubusercontent.com/dopeytree/TVx/main/public/screenshot-1.png</Screenshot>
    <Screenshot>https://raw.githubusercontent.com/dopeytree/TVx/main/public/screenshot-2.png</Screenshot>
    <Screenshot>https://raw.githubusercontent.com/dopeytree/TVx/main/public/screenshot-3.png</Screenshot>
    <Screenshot>https://raw.githubusercontent.com/dopeytree/TVx/main/public/screenshot-4.png</Screenshot>
    <Screenshot>https://raw.githubusercontent.com/dopeytree/TVx/main/public/screenshot-5.png</Screenshot>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2025-10-21

        Add missing environment variables

        ### 2025-10-13

        Initial release
    </Changes>
    <Requires>
        Requires an M3U playlist and optional XMLTV (EPG) guide file. Tunarr or Dizquetv paired with Plex, Emby or Jellyfin recommended.
    </Requires>
    <Config Name="Web UI Port" Target="80" Default="8777" Mode="tcp" Description="Container Port: 80" Type="Port" Display="always-hide" Required="true" Mask="false">8777</Config>
    <Config Name="M3U URL" Target="VITE_M3U_URL" Default="http://your-tunarr-ip-address:8000/api/channels.m3u" Description="M3U URL for IPTV stream" Type="Variable" Display="always-hide" Required="true" Mask="false">http://your-tunarr-ip-address:8000/api/channels.m3u</Config>
    <Config Name="XMLTV URL" Target="VITE_XMLTV_URL" Default="http://your-tunarr-ip-address:8000/api/xmltv.xml" Description="EPG URL for IPTV stream" Type="Variable" Display="always-hide" Required="true" Mask="false">http://your-tunarr-ip-address:8000/api/xmltv.xml</Config>
    <Config Name="App Data" Target="/config" Default="/mnt/user/appdata/tvx/config" Mode="rw" Description="Path for persistent storage of settings, configuration files" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/tvx/config</Config>
</Container>

=== nwithan8/unraid_templates/templates/llama_swap.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/template_schema.xsd template_schema.xsd">
    <Name>llama-swap</Name>
    <Repository>ghcr.io/mostlygeek/llama-swap:unified-cuda</Repository>
    <Registry>ghcr.io/mostlygeek/llama-swap</Registry>
    <Branch>
        <Tag>unified-cuda</Tag>
        <TagDescription>Latest stable release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <WebUI>http://[IP]:[PORT:8080]/</WebUI>
    <Privileged>false</Privileged>
    <Support>https://github.com/mostlygeek/llama-swap/issues</Support>
    <Project>https://github.com/mostlygeek/llama-swap</Project>
    <Overview>
        Run multiple generative AI models on your machine and hot-swap between them on demand. llama-swap works with any OpenAI and Anthropic API compatible server and is used by thousands of people to power their local AI workflows.
    </Overview>
    <Beta>False</Beta>
    <Category>AI: Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>ai models llama ollama swap change multiple openai anthropic api server</ExtraSearchTerms>
    <Icon>https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/llama-swap-icon.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/llama_swap.xml</TemplateURL>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2026-06-28

        Initial release
    </Changes>
    <Requires>
        Expects a `config.yaml` file at the Config File path BEFORE starting the container.
    </Requires>
    <ExtraParams>--runtime=nvidia --gpus all</ExtraParams>
    <Config Name="Web UI Port" Target="8080" Default="9292" Mode="tcp" Description="Container Port: 8080" Type="Port" Display="always-hide" Required="true" Mask="false">9292</Config>
    <Config Name="Config File" Target="/etc/llama-swap/config/config.yaml" Default="/mnt/user/appdata/llama_swap/config.yaml" Description="Path to the config file" Required="true" Mask="false">/mnt/user/appdata/llama_swap/config.yaml</Config>
    <Config Name="Models Storage" Target="/models" Default="/mnt/user/appdata/llama_swap/models" Description="Path to models" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/llama_swap/models</Config>
</Container>

=== nwithan8/unraid_templates/templates/retrom.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/template_schema.xsd template_schema.xsd">
    <Name>Retrom</Name>
    <Repository>ghcr.io/jmberesford/retrom-service:latest</Repository>
    <Registry>ghcr.io/jmberesford/retrom-service</Registry>
    <Branch>
        <Tag>latest</Tag>
        <TagDescription>Latest stable release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <WebUI>http://[IP]:[PORT:3000]</WebUI>
    <Privileged>false</Privileged>
    <Support>https://github.com/JMBeresford/retrom/issues</Support>
    <Project>https://github.com/JMBeresford/retrom</Project>
    <Overview>
        Retrom is a centralized game library management service that allows you to host your games on a single device, and connect clients on any amount of other devices to (un)install/download and subsequently launch said games locally.
    </Overview>
    <Category>MediaApp:Other MediaServer:Other Productivity: Tools: Other: Status:Stable</Category>
    <Icon>https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/retrom-icon.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/retrom.xml</TemplateURL>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2024-10-09

        Initial release
    </Changes>
    <Requires>
        This application expects a `config.json` file to be present in the "Config Data" directory. See documentation: https://github.com/JMBeresford/retrom/blob/main/README.md#docker-recommended &#xD;
        [br]
        This application requires a separate Postgres database. Configuration data for the Postgres container (host, username, password, database name) should be updated in the `config.json` file.
    </Requires>
    <Config Name="Web UI Port" Target="3000" Default="3000" Mode="tcp" Description="Access web interface" Type="Port" Display="always-hide" Required="true" Mask="false">3000</Config>
    <Config Name="Service Port" Target="5101" Default="5101" Mode="tcp" Description="Allow external clients to connect to server" Type="Port" Display="always-hide" Required="true" Mask="false">5101</Config>
    <Config Name="Library" Target="/library" Default="" Mode="rw" Description="Library of games" Type="Path" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Config data" Target="/config" Default="/mnt/user/appdata/retrom/config" Mode="rw" Description="Config data for application" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/retrom/config</Config>
</Container>

=== nwithan8/unraid_templates/templates/smartermail.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/template_schema.xsd template_schema.xsd">
    <Name>SmarterMail</Name>
    <Repository>smartertools/smartermail:latest</Repository>
    <Registry>https://hub.docker.com/r/smartertools/smartermail</Registry>
    <Branch>
        <Tag>latest</Tag>
        <TagDescription>Latest stable release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <WebUI>http://[IP]:[PORT:80]/</WebUI>
    <Privileged>false</Privileged>
    <Support>https://help.smartertools.com</Support>
    <Project>https://www.smartertools.com/</Project>
    <Overview>
        SmarterMail is the Microsoft Exchange alternative, offering the only other email, groupware, and collaboration server on the market with native MAPI support, the same protocol that powers Exchange and Outlook.    </Overview>
    <Beta>False</Beta>
    <Category>Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>email mail server collaboration groupware exchange outlook mapi</ExtraSearchTerms>
    <Icon>https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/smartermail-icon.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/smartermail.xml</TemplateURL>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2025-10-20

        Initial release
    </Changes>
    <Config Name="HTTP Web UI Port" Target="80" Default="1080" Mode="tcp" Description="Container Port: 80" Type="Port" Display="always-hide" Required="true" Mask="false">1080</Config>
    <Config Name="HTTPS Web UI Port" Target="443" Default="1443" Mode="tcp" Description="Container Port: 443" Type="Port" Display="always-hide" Required="true" Mask="false">1443</Config>
    <Config Name="HTTPS UDP Port" Target="443" Default="1443" Mode="udp" Description="Container Port: 443" Type="Port" Display="always-hide" Required="true" Mask="false">1443</Config>
    <Config Name="SMTP Port" Target="25" Default="1025" Mode="tcp" Description="Container Port: 25" Type="Port" Display="always-hide" Required="true" Mask="false">1025</Config>
    <Config Name="SMTP SSL Port" Target="465" Default="1465" Mode="tcp" Description="Container Port: 465" Type="Port" Display="always-hide" Required="true" Mask="false">1465</Config>
    <Config Name="SMTP TLS Port" Target="587" Default="1587" Mode="tcp" Description="Container Port: 587" Type="Port" Display="always-hide" Required="true" Mask="false">1587</Config>
    <Config Name="IMAP Port" Target="143" Default="1143" Mode="tcp" Description="Container Port: 143" Type="Port" Display="always-hide" Required="true" Mask="false">1143</Config>
    <Config Name="IMAP SSL Port" Target="993" Default="1993" Mode="tcp" Description="Container Port: 993" Type="Port" Display="always-hide" Required="true" Mask="false">1993</Config>
    <Config Name="POP3 Port" Target="110" Default="1110" Mode="tcp" Description="Container Port: 110" Type="Port" Display="always-hide" Required="true" Mask="false">1110</Config>
    <Config Name="POP3 SSL Port" Target="995" Default="1995" Mode="tcp" Description="Container Port: 995" Type="Port" Display="always-hide" Required="true" Mask="false">1995</Config>
    <Config Name="XMPP Port" Target="5222" Default="15222" Mode="tcp" Description="Container Port: 5222" Type="Port" Display="always-hide" Required="true" Mask="false">15222</Config>
    <Config Name="App Data" Target="/app/Data" Default="/mnt/user/appdata/smartermail/data" Description="Path to the data folder" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/smartermail/data</Config>
    <Config Name="System Data" Target="/app/SystemData" Default="/mnt/user/appdata/smartermail/systemdata" Description="Path to the system data folder" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/smartermail/systemdata</Config>
</Container>

=== nwithan8/unraid_templates/templates/tunarr.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/template_schema.xsd template_schema.xsd">
    <Name>Tunarr</Name>
    <Repository>ghcr.io/chrisbenincasa/tunarr:latest</Repository>
    <Registry>https://github.com/chrisbenincasa/tunarr/pkgs/container/tunarr</Registry>
    <Branch>
        <Tag>latest</Tag>
        <TagDescription>Latest development release</TagDescription>
    </Branch>
    <Branch>
        <Tag>edge</Tag>
        <TagDescription>Edge release (every 2 hours) release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <WebUI>http://[IP]:[PORT:8000]/</WebUI>
    <Privileged>false</Privileged>
    <Support>https://forums.unraid.net/topic/133764-support-grtgbln-docker-templates</Support>
    <Project>https://tunarr.com</Project>
    <Overview>
        Create live TV channels from media on your Plex servers, and more!&#xD;
        Access your channels by adding the spoofed Tunarr HDHomerun tuner to Plex, Jellyfin, or Emby. Or utilize generated M3U files with any 3rd party IPTV player app.&#xD;
        Tunarr is a fork of dizqueTV.&#xD;
        [br]
        **Nvidia GPU Use:**&#xD;
        Using the Unraid Nvidia Plugin to install a version of Unraid with the Nvidia Drivers installed and add **--runtime=nvidia** to [b]"extra parameters"[/b] (switch on advanced view) and copy your **GPU UUID** to **NVIDIA_VISIBLE_DEVICES.**&#xD;
        [br]
        **Intel GPU Use:**&#xD;
        Edit your **go** file to include **modprobe i915**, save and reboot, then add **--device=/dev/dri** to **"extra parameters"** (switch on advanced view)
    </Overview>
    <Beta>True</Beta>
    <Category>MediaApp:Video MediaServer:Video Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>Tuner TV Media Video Live Channels HDHomerun Emby Plex Jellyfin IPTV Unraid Nvidia Intel ErsatzTV dizqueTV pseudoTV</ExtraSearchTerms>
    <Icon>https://tunarr.com/assets/tunarr.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/tunarr.xml</TemplateURL>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ## 2025-08-11

        Remove hardware-acceleration-specific tags, no longer needed

        ## 2024-08-04

        Default to the latest tag
        Fixes default configuration data location after https://github.com/chrisbenincasa/tunarr/pull/643

        ## 2024-06-16

        Adjust configuration path, add backup path

        ### 2024-06-12

        Fix default PGID and PUID

        ### 2024-06-10

        Fix default branch

        ### 2024-05-30

        Initial release
    </Changes>
    <Requires>
        Don't forget to add Nvidia- or Intel-specific parameters for hardware transcoding. Enable **Advanced View** and see **Overview** for details.
    </Requires>
    <Config Name="Web UI Port" Target="8000" Default="8000" Mode="tcp" Description="Container Port: 8000" Type="Port" Display="always" Required="true" Mask="false">8000</Config>
    <Config Name="Configuration data" Target="/config/tunarr" Default="/mnt/user/appdata/tunarr/config" Mode="rw" Description="Path to configuration data" Type="Path" Display="advanced" Required="true" Mask="false">/mnt/user/appdata/tunarr/config</Config>
    <Config Name="dizqueTV migration data" Target="/.dizquetv" Default="" Mode="ro" Description="Path to old dizqueTV installation for migration" Type="Path" Display="advanced" Required="false" Mask="false" />
    <Config Name="Nvidia Visible Devices" Target="NVIDIA_VISIBLE_DEVICES" Default="all" Mode="" Description="Nvidia Visible Devices (Optional - Requires Nvidia GPU and Unraid Nvidia build)" Type="Variable" Display="always-hide" Required="false" Mask="false"/>
    <Config Name="Nvidia Driver Capabilities" Target="NVIDIA_DRIVER_CAPABILITIES" Default="all" Mode="" Description="Nvidia Driver Capabilities (Optional - Requires Nvidia GPU and Unraid Nvidia build)" Type="Variable" Display="advanced-hide" Required="false" Mask="false">all</Config>
    <Config Name="PUID" Target="PUID" Default="099" Description="" Type="Variable" Display="advanced" Required="true" Mask="false">099</Config>
    <Config Name="PGID" Target="PGID" Default="100" Description="" Type="Variable" Display="advanced" Required="true" Mask="false">100</Config>
</Container>
