=== nwithan8/unraid_templates/templates/template_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Container">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="^[A-Za-z0-9\s\-]*$"/>  <!-- Non-empty string, letters, numbers, spaces, hyphens -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Repository" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[\w\-_.]+/[\w\-_/]+:[\w\-_.]+"/> <!-- Example: author/repo:tag -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Registry" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[\S\s]+"/> <!-- Non-empty string -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Branch" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Tag" type="xs:string"/>
                            <xs:element name="TagDescription" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Network" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="WebUI" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://\[IP\]:\[PORT:\d{1,5}\].*"/> <!-- Technically allows ports larger than 65535 -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Shell" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Privileged" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Support" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+"/> <!-- URL pattern -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Project" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+"/> <!-- URL pattern -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Overview" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[\S\s]+"/> <!-- Non-empty string -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Beta" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="True"/>
                            <xs:enumeration value="False"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Category" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="([^:]+:[^:\s]*\s?)+"/> <!-- Any amount of "Category:" or "Category:Subcategory" elements-->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ExtraSearchTerms" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Icon" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+\.(png|jpg|jpeg|gif|svg)"/> <!-- URL pattern for image files -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Banner" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+\.(png|jpg|jpeg|gif|svg)"/> <!-- URL pattern for image files -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="TemplateURL" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+\.xml"/> <!-- URL pattern for XML files -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Screenshot" minOccurs="0" maxOccurs="unbounded">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+\.(png|jpg|jpeg|gif|svg)"/> <!-- URL pattern for image files -->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Maintainer" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="WebPage">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="https?://.+"/> <!-- URL pattern -->
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Changes" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Requires" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="ExtraParams" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="PostArgs" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Config" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="Name" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[\S\s]+"/> <!-- Non-empty string -->
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="Target" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[\S\s]+"/> <!-- Non-empty string -->
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="Default" type="xs:string" use="required"/>
                                <xs:attribute name="Mode" type="xs:string"/>
                                <xs:attribute name="Description" type="xs:string" use="required"/>
                                <xs:attribute name="Type" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="Port"/>
                                            <xs:enumeration value="Path"/>
                                            <xs:enumeration value="Variable"/>
                                            <xs:enumeration value="Label"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="Display" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="always"/>
                                            <xs:enumeration value="always-hide"/>
                                            <xs:enumeration value="advanced"/>
                                            <xs:enumeration value="advanced-hide"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="Required" type="xs:boolean" use="required"/>
                                <xs:attribute name="Mask" type="xs:boolean" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== nwithan8/unraid_templates/templates/superstreamer_stitcher.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/template_schema.xsd template_schema.xsd">
    <Name>Superstreamer - Stitcher</Name>
    <Repository>superstreamerapp/stitcher:latest</Repository>
    <Registry>https://hub.docker.com/r/superstreamerapp/stitcher</Registry>
    <Branch>
        <Tag>latest</Tag>
        <TagDescription>Latest stable release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <Privileged>false</Privileged>
    <Support>https://superstreamer.xyz/guide/getting-started</Support>
    <Project>https://superstreamer.xyz</Project>
    <Overview>
        Superstreamer is here to make video delivery simple. Imagine having everything you need in one platform â€” starting with your raw video, Superstreamer helps you transcode it, package it into HLS playlists, and upload it to S3 with ease. You can even create custom playlists for each viewer, adding bumpers, ads, or filters on the fly.
    </Overview>
    <Category>MediaApp:Music MediaApp:Video MediaServer:Music MediaServer:Video Cloud: Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>music video hosting transcode server streaming download playlists queue Stitcher ads advertisements sponsors</ExtraSearchTerms>
    <Icon>https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/superstreamer-icon.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/superstreamer_stitcher.xml</TemplateURL>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2025-03-30

        Update environmental variables

        ### 2024-10-14

        Initial release
    </Changes>
     <Requires>
        This is the Stitcher for the Superstreamer suite. It requires other Superstreamer containers to be running. &#xD;
    </Requires>
    <Config Name="Application Port" Target="52002" Default="52002" Mode="tcp" Description="Port over which other containers will communicate with this container" Type="Port" Display="always-hide" Required="true" Mask="false">52002</Config>
    <Config Name="Redis - URI" Target="REDIS_URI" Default="redis://localhost:6379" Description="URI of the Redis database" Type="Variable" Display="always-hide" Required="true" Mask="false">redis://localhost:6379</Config>
    <Config Name="Public API Endpoint" Target="PUBLIC_API_ENDPOINT" Default="http://localhost:520001" Description="Publicly accessible URL for Superstreamer API container. Replace with your IP or domain." Type="Variable" Display="always-hide" Required="true" Mask="false">http://localhost:52001</Config>
    <Config Name="Secret" Target="SUPER_SECRET" Default="" Description="Secret key for the API" Type="Variable" Display="always-hide" Required="true" Mask="true"/>
    <Config Name="Public Stitcher Endpoint" Target="PUBLIC_STITCHER_ENDPOINT" Default="http://localhost:52002" Description="Publicly accessible URL for Superstreamer Stitcher container. Replace with your IP or domain." Type="Variable" Display="always-hide" Required="true" Mask="false">http://localhost:52002</Config>
    <Config Name="Public AWS S3 Endpoint" Target="PUBLIC_S3_ENDPOINT" Default="" Description="Publicly accessible URL for S3 storage bucket used to store media files." Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Internal App Port" Target="PORT" Default="52002" Mode="tcp" Description="Internal port for container. Not recommended to change." Type="Port" Display="advanced-hide" Required="true" Mask="false">52002</Config>
</Container>

=== nwithan8/unraid_templates/templates/orpheusbetter.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/template_schema.xsd template_schema.xsd">
    <Name>orpheusbetter</Name>
    <Repository>ghcr.io/quorn23/orpheusbetter-docker:master</Repository>
    <Registry>ghcr.io/quorn23/orpheusbetter-docker</Registry>
    <Branch>
        <Tag>master</Tag>
        <TagDescription>Latest release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <Privileged>false</Privileged>
    <Support>https://github.com/quorn23/orpheusbetter-docker/issues</Support>
    <Project>https://github.com/quorn23/orpheusbetter-docker</Project>
    <Overview>
        orpheusbetter is a script which automatically transcodes and uploads these files to Orpheus.
    </Overview>
    <Beta>False</Beta>
    <Category>MediaApp:Music MediaServer:Music Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>flac orpheus scan transcode audio automation upload</ExtraSearchTerms>
    <Icon>https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/orpheusbetter-icon.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/orpheusbetter.xml</TemplateURL>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2025-06-07

        Initial release
    </Changes>
    <Config Name="Data Path" Target="/data/torrents" Default="" Description="Path to torrents directory" Type="Path" Display="advanced-hide" Required="true" Mask="false"/>
    <Config Name="Config Path" Target="/config/.orpheusbetter" Default="/mnt/user/appdata/orpheusbetter/config" Description="Path to the orpheusbetter config directory" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/orpheusbetter/config</Config>
</Container>

=== nwithan8/unraid_templates/templates/bark.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/template_schema.xsd template_schema.xsd">
    <Name>Bark Server</Name>
    <Repository>finab/bark-server:latest</Repository>
    <Registry>https://hub.docker.com/r/finab/bark-server</Registry>
    <Branch>
        <Tag>latest</Tag>
        <TagDescription>Latest stable release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <WebUI>http://[IP]:[PORT:8080]/</WebUI>
    <Privileged>false</Privileged>
    <Support>https://github.com/Finb/bark-server/issues</Support>
    <Project>https://bark.day.app</Project>
    <Overview>
        Backend for Bark, an iOS app to receive custom push notifications
    </Overview>
    <Beta>False</Beta>
    <Category>MediaApp:Other Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>bark server push notification ios apple android iphone sms apprise</ExtraSearchTerms>
    <Icon>https://bark.day.app/_media/Icon.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/bark.xml</TemplateURL>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2025-01-31

        Initial release
    </Changes>
    <Config Name="API Port" Target="8080" Default="8080" Mode="tcp" Description="Container Port: 8080" Type="Port" Display="always-hide" Required="true" Mask="false">8080</Config>
    <Config Name="Data Path" Target="/data" Default="/mnt/user/appdata/bark/data" Description="Path to data files" Type="Path" Display="always-hide" Required="true" Mask="false">/mnt/user/appdata/bark/data</Config>
</Container>

=== nwithan8/unraid_templates/templates/answer.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/template_schema.xsd template_schema.xsd">
    <Name>Answer</Name>
    <Repository>apache/answer:latest</Repository>
    <Registry>https://hub.docker.com/r/apache/answer</Registry>
    <Branch>
        <Tag>latest</Tag>
        <TagDescription>Latest stable release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <WebUI>http://[IP]:[PORT:80]/install</WebUI>
    <Privileged>false</Privileged>
    <Support>https://answer.apache.org/docs</Support>
    <Project>https://answer.apache.org</Project>
    <Overview>
        Apache Answer helps you to build a community between your users and your team. It's a place where you can share your knowledge and help your users to solve their problems.    </Overview>
    <Beta>False</Beta>
    <Category>Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>apache answer knowledgebase faq support community forum question</ExtraSearchTerms>
    <Icon>https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/answer-icon.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/answer.xml</TemplateURL>
    <Screenshot>https://answer.apache.org/assets/images/profile-laptop@2x-c4b7098e1429603fe6b8409621accf65.png</Screenshot>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2025-10-20

        Initial release
    </Changes>
    <Config Name="Web UI Port" Target="80" Default="9080" Mode="tcp" Description="Container Port: 80" Type="Port" Display="always-hide" Required="true" Mask="false">9080</Config>
    <Config Name="Data Path" Target="/data" Default="/mnt/user/appdata/answer/data" Description="Path to the data folder" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/answer/data</Config>
</Container>

=== nwithan8/unraid_templates/templates/pgvector13.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/template_schema.xsd template_schema.xsd">
    <Name>pgvector-13</Name>
    <Repository>pgvector/pgvector:pg13</Repository>
    <Registry>https://hub.docker.com/r/pgvector/pgvector</Registry>
    <Network>bridge</Network>
    <Privileged>false</Privileged>
    <Support>https://github.com/pgvector/pgvector/issues</Support>
    <Project>https://github.com/pgvector/pgvector</Project>
    <Overview>
        Open-source vector similarity search for Postgres.
    </Overview>
    <Beta>False</Beta>
    <Category>Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>postgres vector database similarity search embedding</ExtraSearchTerms>
    <Icon>https://raw.githubusercontent.com/nwithan8/unraid_templates/master/images/pgvector-icon.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/pgvector13.xml</TemplateURL>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2026-01-18

        Initial release
    </Changes>
    <Config Name="Port" Target="5432" Default="5432" Mode="tcp" Description="Container Port: 5432" Type="Port" Display="always-hide" Required="true" Mask="false">5432</Config>
    <Config Name="Database Storage Path" Target="/var/lib/postgresql" Default="/mnt/user/appdata/pgvector13" Description="Path to store database files" Type="Path" Mode="rw" Display="always-hide" Required="true" Mask="false">/mnt/user/appdata/pgvector13</Config>
    <Config Name="Username" Target="POSTGRES_USER" Default="" Description="PostgreSQL superuser name" Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Password" Target="POSTGRES_PASSWORD" Default="" Description="PostgreSQL superuser password" Type="Variable" Display="always-hide" Required="true" Mask="true"/>
    <Config Name="Database Name" Target="POSTGRES_DB" Default="" Description="Initial database name" Type="Variable" Display="always-hide" Required="true" Mask="false"/>
</Container>

=== nwithan8/unraid_templates/templates/valhalla.xml
<?xml version="1.0"?>
<Container version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/template_schema.xsd template_schema.xsd">
    <Name>Valhalla</Name>
    <Repository>ghcr.io/valhalla/valhalla:latest</Repository>
    <Registry>ghcr.io/valhalla/valhalla</Registry>
    <Branch>
        <Tag>latest</Tag>
        <TagDescription>Latest stable release</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <Privileged>false</Privileged>
    <Support>https://valhalla.github.io/valhalla</Support>
    <Project>https://github.com/valhalla/valhalla</Project>
    <Overview>
        An open source routing engine and accompanying libraries for use with OpenStreetMap data. Valhalla also includes tools like time+distance matrix computation, isochrones, elevation sampling, map matching and tour optimization (Travelling Salesman).
    </Overview>
    <Beta>False</Beta>
    <Category>Productivity: Tools: Other: Status:Stable</Category>
    <ExtraSearchTerms>routing openstreetmap osm map matching isochrones elevation matrix calculation traveling salesman time distance tour optimization route plan</ExtraSearchTerms>
    <Icon>https://valhalla.github.io/valhalla/images/valhalla.png</Icon>
    <TemplateURL>https://raw.githubusercontent.com/nwithan8/unraid_templates/main/templates/valhalla.xml</TemplateURL>
    <Maintainer>
        <WebPage>https://github.com/nwithan8</WebPage>
    </Maintainer>
    <Changes>
        ### 2025-01-28

        Initial release
    </Changes>
    <Config Name="API Port" Target="8002" Default="8002" Mode="tcp" Description="Container Port: 8002" Type="Port" Display="always-hide" Required="true" Mask="false">8002</Config>
    <Config Name="Tile URLs" Target="tile_urls" Default="https://download.geofabrik.de/europe/andorra-latest.osm.pbf" Description="Space-separated list of URLs. Remove if Use Local Tiles is enabled." Type="Variable" Display="always" Required="true" Mask="false">https://download.geofabrik.de/europe/andorra-latest.osm.pbf</Config>
    <Config Name="Use Local Tiles" Target="use_tiles_ignore_pbf" Default="False|True" Description="Use a local tile.tar file instead of downloading and building" Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Build Tar" Target="build_tar" Default="True|Force|False" Description="True creates a tarball of the tiles including an index which allows for extremely faster graph loading after reboots. Force will do the same, but first delete the existing tarball." Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Force Rebuild" Target="force_rebuild" Default="False|True" Description="Force a rebuild of the routing tiles and sets (overrides Build Tar)" Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Build Elevation" Target="build_elevation" Default="False|True|Force" Description="True downloads elevation tiles which are covering the routing graph. Force will do the same, but first delete any existing elevation tiles." Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Build Admins" Target="build_admins" Default="False|True|Force" Description="True builds the admin database needed for things like border-crossing penalties and detailed routing responses. Force will do the same, but first delete the existing database." Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Build Time Zones" Target="build_time_zones" Default="False|True|Force" Description="True builds the timezone database which is needed for time-dependent routing. Force will do the same, but first delete the existing database." Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Build Transit" Target="build_transit" Default="False|True|Force" Description="True will attempt to build transit tiles if none exist yet. Force will remove existing transit and routing tiles." Type="Variable" Display="always-hide" Required="true" Mask="false"/>
    <Config Name="Custom Files" Target="/custom_files" Default="/mnt/user/appdata/valhalla/custom_files" Description="Path to custom files." Type="Path" Display="always-hide" Required="true" Mask="false">/mnt/user/appdata/valhalla/custom_files</Config>
    <Config Name="GTFS Feeds" Target="/gtfs_feeds" Default="/mnt/user/appdata/valhalla/gtfs_feeds" Description="Path to GTFS feeds. Remove if Build Transit is disabled." Type="Path" Display="always" Required="true" Mask="false">/mnt/user/appdata/valhalla/gtfs_feeds</Config>
    <Config Name="Tileset Name" Target="tileset_name" Default="valhalla_tiles" Description="The name of the resulting graph on disk. Very useful in case you want to build multiple datasets in the same directory." Type="Variable" Display="advanced-hide" Required="true" Mask="false">valhalla_tiles</Config>
    <Config Name="Traffic Name" Target="traffic_name" Default="traffic.tar" Description="The name of the traffic.tar. Again, useful for serving multiple traffic archives from the same directory. If empty, no traffic archive will be built." Type="Variable" Display="advanced-hide" Required="false" Mask="false">traffic.tar</Config>
    <Config Name="Path Extensions" Target="path_extension" Description="This path will be appended to the custom_files path and will be the directory where all files will be created. Can be very useful in certain deployment scenarios. No leading/trailing path separator allowed." Type="Variable" Display="advanced-hide" Required="false" Mask="false"/>
    <Config Name="Update Existing Config" Target="update_existing_config" Default="True|False" Description="True updates missing keys in existing valhalla.json. Useful for updating stale config files to include newly introduced config parameters." Type="Variable" Display="advanced-hide" Required="true" Mask="false"/>
    <Config Name="Use Default Speed Config" Target="use_default_speeds_config" Default="False|True" Description="True loads a JSON file used to enhance default speeds (or falls back to an existing custom_files/default_speeds.json) and sets the respective config entry. More details: https://github.com/OpenStreetMapSpeeds/schema" Type="Variable" Display="advanced-hide" Required="true" Mask="false"/>
    <Config Name="Default Speed Config URL" Target="default_speeds_config_url" Default="https://raw.githubusercontent.com/OpenStreetMapSpeeds/schema/master/default_speeds.json" Description="Remote location of the default_speeds_config JSON." Type="Variable" Display="advanced-hide" Required="true" Mask="false">https://raw.githubusercontent.com/OpenStreetMapSpeeds/schema/master/default_speeds.json</Config>
    <Config Name="Serve Tiles" Target="serve_tiles" Default="True|False" Description="Serve tiles from the container. If false, only build the graph." Type="Variable" Display="advanced-hide" Required="true" Mask="false"/>
    <Config Name="Server Threads" Target="server_threads" Default="2" Description="Number of threads to use for the server" Type="Variable" Display="advanced-hide" Required="true" Mask="false">2</Config>
</Container>
